#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - yarn install

script:
  - ng build --prod

# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN
